### ISSUE TITLE
How easy would it be to resize the video / position it during playback?

### ISSUE THREAD

**Issue by jfrux** [vincentf06/cordova-brightcove-player#3]
Thinking about forking this and adding some sort of resize ability... but not sure if it's feasible with Cordova.

**Comment by vincentf06** [comment]
> Thinking about forking this and adding some sort of resize ability... but not sure if it's feasible with Cordova.

from brightcove's docs
Set the player view to match the video container from your layout (videoView) when it resizes.

```
self.playerView.frame = self.videoView.bounds;
self.playerView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
```

**Comment by jfrux** [comment]
You’re in the same boat as me.
I think it’s possible... and probably not that much code... it’s just a matter of getting all of the features one would need.

I definitely would use it... although I’m not certain a ton of people would be using it... I’m only using it because I want to tap native libraries on AndroidTV and FireTV devices.

I’d love to be able to tap into native DAI libs and things.

**Comment by jfrux** [comment]
Omg my bad... you were quoting me and it came through my email as your own thoughts lmao... hilarious.  My fault! Thank you for your response!
